#!/usr/bin/env bash
# Prints a string 10 times using while loop and on the ninth iteration it prints hi

i=0

while [ $i -lt 10 ]; do
    echo "Best School"

    if [ $i -eq 8 ]; then
        echo "hi"
    fi
    ((i++))
done
