#!/usr/bin/env bash
# alx school file checker

file="school"

if [ -e "$file" ]; then

    echo "school file exists"

    if [ ! -s "$file" ]; then
        echo "school file is empty"

        if [ -f "$file" ]; then
            echo "school is a regular file"
        fi

    else
        echo "school file is not empty"

        if [ -f "$file" ]; then
            echo "school is a regular file"
        fi
    fi

else
    echo "school file does not exist"
fi
